console.log("log")
console.info("info")
console.warn("warn")
console.error("error")
console.assert("err" != false)
console.assert("err" == false)
console.table(console)
console.time("p1")
console.timeEnd("p1")